#!/bin/bash -l
if [ -z "$3" ]; then
  echo " Usage: <day> <first run> <last runA> <optional #events> "
  exit 1
fi
DAY=$1
FIRST=$2
LAST=$3

if [ -z "$4" ]; then
  NEV=0
else 
  NEV=$4
fi

DATADIR=/global/homes/m/mgold/data/2017/PDS_beamtime_files
OUTDIR=/global/homes/m/mgold/data/2017/pdsOuput/
ATTRIB=alternate

echo " DAY = $DAY FIRST = $FIRST LAST=$LAST "
echo " ATTRIB = $ATTRIB  "
echo " DATADIR=$DATADIR "
echo " OUTDIR=$OUTDIR"

ZERO=0

for ((a=$FIRST; a <= $LAST ; a++)) ; do  # Double parentheses, and naked "LIMIT"
  length=${#a}
  echo "length of a is $length zero = $ZERO"
  while [ $length -lt 4 ] ; do
    a=$ZERO$a
    length=${#a}
  done
  echo "a = $a "
  TAG=07-$DAY-${a}_0
  INFILE=PDSout_${TAG}.root
  if [  -e $DATADIR/$INFILE ]; then
    JOBNAME=pdsjob-$TAG-$ATTRIB.sh
    if [ -e $JOBNAME ]; then
      echo remove $JOBNAME 
      rm $JOBNAME
    fi

    echo creating job qsub -l h_vmem=2G $JOBNAME 
    echo "#!/bin/bash -l" >> $JOBNAME
    echo "export ROOTSYS=/project/projectdirs/captain/releases/LCGCMT/2.0.4/LCG_Settings/../EXTERNALS/ROOT/5.34.34/x86_64-linux-gcc44-opt" >> $JOBNAME
    echo "source $ROOTSYS/bin/thisroot.sh" >> $JOBNAME
    echo "/global/homes/m/mgold/mgold/pdsAnalysis/runAna $TAG $NEV" >> $JOBNAME
    cat $JOBNAME
    qsub -l h_vmem=2G $JOBNAME 
  else 
    echo "${DATADIR}/${INFILE} NOT FOUND " 
  fi
done
exit 1

