#!/bin/bash
NMAX=0
echo "runs on 07-30"
#echo $(ls pdsData/PDS*.root)
for name in  `ls pdsData/PDS*.root`  ;do 
TAG=${name:15:12};
MONTH=${name:15:2};
DAY=${name:18:2};
SEG=${name:21:4};

if [ "$MONTH" -eq "07" ] && [ "$DAY" -eq "30" ]  ;then  
 echo $TAG $MONTH $DAY $SEG
 echo root  -q -b "pmtAna.cc++(\"$TAG\",$NMAX)"
 root -q -b " pmtAna.cc++(\"$TAG\",$NMAX)"
 else
 echo "skipping $TAG "
fi
done

