#!/bin/bash
if test -z "$1"
then
  echo " <tag> (e.g. 07-12-1900_0) <max events> "
  exit; 
fi
TAG=$1
# default is read all 
if [ -z "$2" ]; then
  NMAX=0
  else 
  NMAX=$2
fi
echo root  -q -b "pmtAna.cc++(\"$TAG\",$NMAX)"
#root -q -b " pmtAna.cc++(\"$TAG\",$NMAX)"
